### ISSUE TITLE
Initial Project Setup and Infrastructure Configuration

### ISSUE THREAD

**Issue by Mujahid55** [Mujahid55/web-node.js-project#1]
## Overview
Set up the initial project infrastructure and development environment for the Tasahil Platform based on the SRS requirements.

## Technical Requirements
- Node.js v18+
- MySQL 8.0+
- AWS Environment Setup

### Development Environment
- [ ] Initialize Node.js project with Express.js
- [ ] Set up EJS template engine
- [ ] Configure MySQL connection and ORM
- [ ] Implement basic project structure
- [ ] Set up linting and code formatting rules

### AWS Infrastructure
- [ ] Provision EC2 instances (2x t3.medium)
- [ ] Set up MySQL RDS (db.t3.small)
- [ ] Configure S3 bucket for file storage
- [ ] Set up CloudWatch monitoring
- [ ] Configure Nginx load balancer

### CI/CD Pipeline
- [ ] Set up GitHub Actions workflow
- [ ] Configure deployment scripts
- [ ] Set up environment variables
- [ ] Implement automated testing pipeline

## Technical Constraints
```yaml
Backend Stack:
- Node.js v18+
- Express.js
- EJS templates
- MySQL 8.0+

Infrastructure:
- AWS EC2 Linux (t3.medium)
- RDS MySQL
- S3 Storage
- CloudWatch
- Nginx Load Balancer
```

## Acceptance Criteria
- [ ] Development environment is fully configured and documented
- [ ] AWS infrastructure is provisioned and accessible
- [ ] CI/CD pipeline is operational
- [ ] All services are properly connected and communicating
- [ ] Basic health monitoring is in place
- [ ] Development team can deploy changes through the pipeline
